name: 自动抓取优选CF IP并同步更新
on:
  # 每3小时小时自动执行
  schedule:
    - cron: '0 */3 * * *'
  # 手动触发测试
  workflow_dispatch:

jobs:
  ip-collect-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予仓库写入权限
    steps:
      # 拉取远程仓库代码
      - name: 拉取远程仓库完整代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      # 安装依赖（已添加fake_useragent）
      - name: 安装Python依赖库
        run: |
          python -m pip install --upgrade pip
          # 关键修复：添加fake_useragent依赖
          pip install requests beautifulsoup4 fake_useragent

      # 执行IP抓取脚本
      - name: 运行IP抓取脚本
        run: python collect_ips.py
        continue-on-error: false

      # 执行IP筛选脚本
      - name: 运行IP筛选脚本
        run: python ip_filter.py
        continue-on-error: false

      # 同步远程代码处理冲突
      - name: 同步远程代码并处理冲突
        run: |
          git fetch origin main
          git merge origin/main -X ours --no-edit || true
          if [ $? -ne 0 ]; then
            git reset --hard origin/main
            git merge --no-ff -X ours HEAD --no-edit
          fi

      # 提交并推送更新
      - name: 提交修改并推送
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          if git status | grep -q -E "ip.txt|ip2.txt"; then
            git add ip.txt ip2.txt
            git commit -m "自动更新：抓取最新优选CF IP（含香港/日本/新加坡筛选）"
            git push origin HEAD:main
            echo "IP更新成功！"
          else
            echo "无新IP更新，无需提交"
          fi

      # 输出文件状态
      - name: 输出最终文件状态
        run: |
          echo "=== ip.txt行数 ==="
          wc -l ip.txt || echo "ip.txt不存在"
          echo "=== ip2.txt行数 ==="
          wc -l ip2.txt || echo "ip2.txt不存在"
